volumes:
  postgresql:

services:
  postgres:
    image: postgres:16.2-alpine3.19
    container_name: postgres_docker
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_hexburger
    ports:
      - "5432:5432"
    networks:
      - hexburger-network
    volumes:
      - postgresql:/var/docker/postgresql

  hexburger:
    build:
      context: .
      dockerfile: Dockerfile
    image: hexburger:latest
    container_name: hexburger-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - hexburger-network

networks:
  hexburger-network:
