apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16.2-alpine3.19
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: db_hexburger
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - exec pg_isready --host localhost
            initialDelaySeconds: 5
            failureThreshold: 3
            periodSeconds: 20
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - exec pg_isready --host localhost
            initialDelaySeconds: 5
            periodSeconds: 20
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc